### ISSUE TITLE
Bootloop in version 1.3.0

### ISSUE THREAD

**Issue by killer7Mod** [manhong2112/DownloadRedirect#18] opened 2017-09-20 14:21 UTC
OS: Lineage 13.0
Android: 6.0.1
Device: Moto E 2015

I no have computer to capture logcat in boot.

**Comment by MacgyverJohnson** [comment] 2017-09-20 15:10
You do not need PC for logcat...u can use another android device for this as well ....Follow this: https://stackoverflow.com/questions/29238774/how-to-use-android-device-as-host-to-pull-logs-from-another-android-device

**Comment by manhong2112** [comment] 2017-09-21 12:51
i guess it may caused by zipalign..but i still need logcat to confirm

**Comment by killer7Mod** [comment] 2017-09-21 18:56
I captured log using liveboot.

I/Xposed  (  402):   Loading class net.manhong2112.downloadredirect.XposedHook
W/XSharedPreferences(  402): getSharedPreferences
W/XSharedPreferences(  402): java.io.IOException: Permission denied while reading /data/data/net.manhong2112.downloadredirect/shared_prefs/pref.xml
W/XSharedPreferences(  402): 	at de.robv.android.xposed.services.ZygoteService.readFile(Native Method)
W/XSharedPreferences(  402): 	at de.robv.android.xposed.services.ZygoteService.readFile(ZygoteService.java:24)
W/XSharedPreferences(  402): 	at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:148)
W/XSharedPreferences(  402): 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:122)
W/XSharedPreferences(  402): 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
W/XSharedPreferences(  402): 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
36,1356,20383817,-;type=1400 audit(1506019514.103:9): avc: denied { call } for uid=0 pid=402 comm="main" scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
E/JavaBinder(  402): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 80)
W/main    (  402): type=1400 audit(0.0:9): avc: denied { call } for uid=0 scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
W/main    (  402): type=1400 audit(0.0:10): avc: denied { call } for uid=0 scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
36,1357,20385934,-;type=1400 audit(1506019514.106:10): avc: denied { call } for uid=0 pid=402 comm="main" scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
W/main    (  402): type=1400 audit(0.0:11): avc: denied { call } for uid=0 scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
E/ServiceManager(  402): error in getService
E/ServiceManager(  402): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
E/ServiceManager(  402): 	at android.os.BinderProxy.transactNative(Native Method)
E/ServiceManager(  402): 	at android.os.BinderProxy.transact(Binder.java:503)
E/ServiceManager(  402): 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
E/ServiceManager(  402): 	at android.os.ServiceManager.getService(ServiceManager.java:55)
E/ServiceManager(  402): 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:864)
E/ServiceManager(  402): 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:85)
E/ServiceManager(  402): 	at android.os.Environment.getExternalStorageDirectory(Environment.java:351)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.Const.<init>(Const.kt:19)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.Const.<clinit>(Const.kt:12)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:29)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:16)
E/ServiceManager(  402): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO.getDownloadConfigs(ConfigDAO.kt)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO.<init>(ConfigDAO.kt:85)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$Companion.getPref(ConfigDAO.kt:22)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.XposedHook.initZygote(XposedHook.kt:53)
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:487)
36,1358,20389264,-;type=1400 audit(1506019514.109:11): avc: denied { call } for uid=0 pid=402 comm="main" scontext=u:r:zygote:s0 tcontext=u:r:servicemanager:s0 tclass=binder permissive=0
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:401)
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
E/JavaBinder(  402): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 84)
E/ServiceManager(  402): error in getService
E/ServiceManager(  402): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
E/ServiceManager(  402): 	at android.os.BinderProxy.transactNative(Native Method)
E/ServiceManager(  402): 	at android.os.BinderProxy.transact(Binder.java:503)
E/ServiceManager(  402): 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
E/ServiceManager(  402): 	at android.os.ServiceManager.getService(ServiceManager.java:55)
E/ServiceManager(  402): 	at android.app.ActivityThread.getPackageManager(ActivityThread.java:1693)
E/ServiceManager(  402): 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:872)
E/ServiceManager(  402): 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:85)
E/ServiceManager(  402): 	at android.os.Environment.getExternalStorageDirectory(Environment.java:351)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.Const.<init>(Const.kt:19)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.Const.<clinit>(Const.kt:12)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:29)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:16)
E/ServiceManager(  402): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO.getDownloadConfigs(ConfigDAO.kt)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO.<init>(ConfigDAO.kt:85)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.ConfigDAO$Companion.getPref(ConfigDAO.kt:22)
E/ServiceManager(  402): 	at net.manhong2112.downloadredirect.XposedHook.initZygote(XposedHook.kt:53)
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:487)
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:401)
E/ServiceManager(  402): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
E/Xposed  (  402):     Failed to load class net.manhong2112.downloadredirect.XposedHook
E/Xposed  (  402): java.lang.ExceptionInInitializerError
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:29)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.ConfigDAO$DownloadConfigs$2.invoke(ConfigDAO.kt:16)
E/Xposed  (  402): 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.ConfigDAO.getDownloadConfigs(ConfigDAO.kt)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.ConfigDAO.<init>(ConfigDAO.kt:85)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.ConfigDAO$Companion.getPref(ConfigDAO.kt:22)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.XposedHook.initZygote(XposedHook.kt:53)
E/Xposed  (  402): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:487)
E/Xposed  (  402): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:401)
E/Xposed  (  402): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
E/Xposed  (  402): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] android.content.pm.IPackageManager.getPackagesForUid(int)' on a null object reference
E/Xposed  (  402): 	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:872)
E/Xposed  (  402): 	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:85)
E/Xposed  (  402): 	at android.os.Environment.getExternalStorageDirectory(Environment.java:351)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.Const.<init>(Const.kt:19)
E/Xposed  (  402): 	at net.manhong2112.downloadredirect.Const.<clinit>(Const.kt:12)
E/Xposed  (  402): 	... 10 more

**Comment by manhong2112** [comment] 2017-09-22 12:05
ok i think i know the reason, but... well it seems that it is caused by world readable flag which is removed in order to fix the FC in Android 7.0.. i will do some test if I am free..

**Comment by killer7Mod** [comment] 2017-09-23 02:50
OK. Thank's

**Comment by manhong2112** [comment] 2017-10-16 13:04
Released new version. It should fixed on N, but I am not sure about 6.x and below

**Comment by killer7Mod** [comment] 2017-10-20 17:44
:) is working on Android 7 but you can not select another app to download

**Comment by manhong2112** [comment] 2017-10-21 03:51
em...i will take a look on it

**Comment by killer7Mod** [comment] 2017-10-21 14:02
I tested with the new update to fix the problem in preference but the problem continues, Logging does not work just like any option within the app

**Comment by manhong2112** [comment] 2017-10-21 16:58
em..it work on my phone actually, maybe you can try again by cleaning data of app?

**Comment by killer7Mod** [comment] 2017-10-22 12:05
I cleaned the data but it did not work, so to be sure, I reinstalled the App and now everything is working fine. thank you for your support.

**Closed** 2017-10-26 16:20 UTC
